import Head from "next/head"
import Image from "next/image"
import { Inter, Nunito } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Link from "next/link"
import { Swiper, SwiperSlide, useSwiper } from "swiper/react"
import {
  A11y,
  EffectCube,
  Navigation,
  Pagination,
  Scrollbar,
} from "swiper/modules"
import "swiper/css"
import "swiper/css/pagination"
import { useState } from "react"
import { Steps } from "@/components/Steps"
const inter = Inter({ subsets: ["latin"] })
const nunito = Nunito({ subsets: ["latin"] })
export default function Home() {
  const SwiperButtonNext = ({ children }) => {
    const swiper = useSwiper()
    return (
      <button
        className={`${styles.btnSecondary} ${nunito.className}`}
        onClick={() => swiper.slideNext()}
      >
        {children}
      </button>
    )
  }

  const [progress, setProgress] = useState(1)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${styles.main} ${nunito.className}`}>
        <div className={styles.mainContainer}>
          <Steps progress={progress} />

          <Swiper
            className={styles.swiperContainer}
            // onSlideChange={handleSlideChange}
            onSlidePrevTransitionStart={() => setProgress(progress - 1)}
            onSlideNextTransitionStart={() => setProgress(progress + 1)}
            parallax={true}
            speed={600}
            pagination={{ type: "progressbar" }}
            allowTouchMove={false}
          >
            <SwiperSlide>
              <div className={styles.swipeCard}>
                {/* <div className={styles.swiperSlide}> */}
                <div className={styles.slideHeader}>
                  <h1>Bienvenido a win</h1>
                  <h4>EL ÚNICO MARKETPLACE DE FÚTBOL</h4>
                  <p>
                    INVIERTE EN EL MERCADO DE PASES Y DISFRUTA DE EXPERIENCIAS
                    ÚNICAS
                  </p>
                </div>
                <div className={styles.swipeBody}>
                  <Image
                    src={"firstSlide.svg"}
                    alt=''
                    width={375}
                    height={500}
                    className={styles.slideImage}
                  />
                </div>
                <div className={styles.continueBtn}>
                  <SwiperButtonNext>Siguiente</SwiperButtonNext>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={styles.swiperSlide}>
                <h1>Slide 2</h1>
                <SwiperButtonNext>Slide</SwiperButtonNext>
              </div>
            </SwiperSlide>
            {/* <SwiperSlide>
              <div className={styles.swiperSlide}>
              <h1>Slide 3</h1>
              <SwiperButtonNext>Slide</SwiperButtonNext>
              </div>
              </SwiperSlide>
              <SwiperSlide>
              <div className={styles.swiperSlide}>
              <h1>Slide 4</h1>
              <SwiperButtonNext>Slide</SwiperButtonNext>
              </div>
              </SwiperSlide>
              <SwiperSlide>
              <div className={styles.swiperSlide}>
                <h1>Slide 5</h1>
                <SwiperButtonNext>Slide</SwiperButtonNext>
              </div>
            </SwiperSlide> */}
          </Swiper>
        </div>

        <nav className={styles.nav}>
          <Link href='#' className={styles.navLinks}>
            <Image src={"/home.svg"} alt='Home' width='24' height='24' />
            <span>Inicio</span>
          </Link>
          <Link href='#' className={styles.navLinks}>
            <Image src={"/search.svg"} alt='Home' width='24' height='24' />
            <span>Buscar</span>
          </Link>
        </nav>
      </main>
    </>
  )
}
